spring.application.name=aitaskmanagement
spring.datasource.url =${SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/taskmanagement}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:@Rohan02}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Hibernate/JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.data.redis.host =${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port = ${SPRING_DATA_REDIS_PORT: 6379}

# Login: 5 requests per minute per IP
app.rate-limit.login.requests=5
app.rate-limit.login.window-seconds=60

# Refresh: 10 requests per minute per IP
app.rate-limit.refresh.requests=10
app.rate-limit.refresh.window-seconds=60

# Authenticated APIs: 100 requests per minute per user
app.rate-limit.authenticated.requests=100
app.rate-limit.authenticated.window-seconds=60


# ===============================
# Presence
# ===============================
# User is considered online if active within 3 minutes
app.presence.online-threshold-seconds=180

# Presence record expires after 30 days
app.presence.ttl-days=30

# Update Redis presence at most once every 30 seconds
app.presence.update-intervals-seconds=30